// Real on-chain snapshot of XikomuFlip on Celo Mainnet.
// Auto-generated by update/activity-report.mjs — refresh with `cd update && npm run report`.
// Used as the SSR/no-JS fallback; /api/stats refreshes these live on the client.
// Every number is verifiable on Celoscan.
export const ONCHAIN_STATS = {
  "flips": 2518,
  "uniquePlayers": 609,
  "winRatePct": 51.5,
  "totalWageredCELO": "134.5232",
  "block": 70259333,
  "contract": "0x7e36d266a721aB82379E1bc73EbCd16C3cef40cd",
  "explorer": "https://celoscan.io/address/0x7e36d266a721aB82379E1bc73EbCd16C3cef40cd"
};
